language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
    - bin/start_json_server.sh
    - phpenv config-add php.ini

before_script:
  - composer install --prefer-source
  - export LANG=C
  - export PATH=vendor/bin:$PATH

script:
  - behat -fprogress --strict

after_failure:
  - cat server.log
  - sudo cat /var/log/nginx/error.log
  - sudo cat /var/log/nginx/access.log